server:
  port: 8086
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      
      
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: contact-service
        uri: lb://contact-service
        predicates:
        - Path=/getContact/**
  application:
    name: Gateway  
